# Generated by Django 4.1.5 on 2023-01-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True, verbose_name='Имя покупателя')),
                ('last_name', models.CharField(max_length=200, null=True, verbose_name='Фамилия покупателя')),
                ('phohe_number', models.CharField(max_length=20, null=True, verbose_name='Телефон покупателя')),
                ('type_of_connection', models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('Telegram', 'Telegram'), ('Email', 'Email')], max_length=100, null=True, verbose_name='Способ связи')),
                ('date_ordered', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='Улица, дом и др.')),
                ('city', models.CharField(max_length=255, null=True, verbose_name='Город')),
                ('country', models.CharField(default='Российская Федерация', max_length=255, null=True, verbose_name='Страна')),
                ('extra', models.CharField(max_length=500, null=True, verbose_name='Дополнительно')),
                ('order_list', models.CharField(max_length=500, null=True, verbose_name='Состав заказа')),
                ('order_cost', models.IntegerField(null=True, verbose_name='Сумма заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('id',),
            },
        ),
    ]
