# Generated by Django 4.1.5 on 2023-01-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type_of_connection',
            field=models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('Telegram', 'Telegram'), ('Email', 'Email')], max_length=100, null=True, verbose_name='Как с вами связаться'),
        ),
    ]
