# Generated by Django 4.1.5 on 2023-01-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_order_type_of_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Улица, дом и др.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=255, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(default='Российская Федерация', max_length=255, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='Имя покупателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='Фамилия покупателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phohe_number',
            field=models.CharField(max_length=20, verbose_name='Телефон покупателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_of_connection',
            field=models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('Telegram', 'Telegram'), ('Email', 'Email')], max_length=100, verbose_name='Как с вами связаться'),
        ),
    ]
