# Generated by Django 4.1.5 on 2023-01-24 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0002_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Имя покупателя')),
                ('last_name', models.CharField(max_length=200, verbose_name='Фамилия покупателя')),
                ('phohe_number', models.CharField(max_length=20, verbose_name='Телефон покупателя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('type_of_connection', models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('Telegram', 'Telegram'), ('Email', 'Email')], max_length=100, verbose_name='Как с вами связаться')),
                ('date_ordered', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('address', models.CharField(max_length=255, verbose_name='Улица, дом и др.')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('country', models.CharField(default='Российская Федерация', max_length=255, verbose_name='Страна')),
                ('extra', models.CharField(max_length=500, null=True, verbose_name='Дополнительно')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачено')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-date_ordered',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='Цена единицы')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='store.product', verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Состав заказа',
                'verbose_name_plural': 'Состав заказа',
            },
        ),
    ]
