# Generated by Django 4.1.5 on 2023-01-17 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True, verbose_name='Имя покупателя')),
                ('last_name', models.CharField(max_length=200, null=True, verbose_name='Фамилия покупателя')),
                ('phohe_number', models.CharField(max_length=20, null=True, verbose_name='Телефон покупателя')),
                ('type_of_connection', models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('Telegram', 'Telegram'), ('Email', 'Email')], max_length=100, null=True, verbose_name='Способ связи')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('complete', models.BooleanField(default=False, verbose_name='Заказ оформлен')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ShipingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='Улица, дом и др.')),
                ('city', models.CharField(max_length=255, null=True, verbose_name='Город')),
                ('country', models.CharField(default='Российская Федерация', max_length=255, null=True, verbose_name='Страна')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('extra', models.CharField(max_length=500, null=True, verbose_name='Дополнительно')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer', verbose_name='Покупатель')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставки',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Название товара')),
                ('color', models.CharField(max_length=255, null=True, verbose_name='Цвет товара')),
                ('size', models.CharField(max_length=255, null=True, verbose_name='Размер товара')),
                ('price', models.IntegerField(verbose_name='Цена товара')),
                ('amount', models.IntegerField(default=0, verbose_name='Остаток товара')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание товара')),
                ('photo', models.ImageField(null=True, upload_to='photos/', verbose_name='Фото товара')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания карточки товара')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения карточки товара')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('id',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, null=True, verbose_name='Количество товара')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления товара в корзину')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order', verbose_name='Номер заказа')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product', verbose_name='Товар в заказе')),
            ],
        ),
    ]
